import os
import glob
import logging
from werkzeug.utils import secure_filename
from flask import Flask, request, render_template, jsonify, send_from_directory
import cv2
import numpy as np

from steganography.embed import embed_message
from steganography.extract import extract_data
from encryption.aes import encrypt_message, decrypt_message
from ai_model.predict import predict_image

logging.basicConfig(level=logging.INFO, format='[%(levelname)s] %(message)s')
logger = logging.getLogger(__name__)

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = 'static/uploads'
app.config['OUTPUT_FOLDER'] = 'static/outputs'

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}

os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)
os.makedirs(app.config['OUTPUT_FOLDER'], exist_ok=True)


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/embed', methods=['POST'])
def handle_embed():
    if 'image' not in request.files or 'message' not in request.form:
        return jsonify({'error': 'Missing image or message'}), 400

    file = request.files['image']
    message = request.form['message'].strip()

    if file.filename == '':
        return jsonify({'error': 'No file selected'}), 400

    if not allowed_file(file.filename):
        return jsonify({'error': 'Invalid file type. Please upload a PNG or JPG image.'}), 400

    if not message:
        return jsonify({'error': 'Message cannot be empty'}), 400

    filename = secure_filename(file.filename)
    # Always output as PNG (lossless) regardless of input format
    out_basename = os.path.splitext(filename)[0]
    input_path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
    file.save(input_path)

    try:
        # Load image in BGR
        input_img = cv2.imread(input_path)
        if input_img is None:
            return jsonify({'error': 'Failed to read image. Ensure it is a valid image file.'}), 400

        # CRITICAL: Resize to 128x128 BEFORE embedding — CNN trained on 128x128
        if input_img.shape[0] != 128 or input_img.shape[1] != 128:
            input_img = cv2.resize(input_img, (128, 128), interpolation=cv2.INTER_AREA)
            logger.info(f"Resized cover image to 128×128")

        # Embed (handles AES encryption internally)
        stego_img = embed_message(input_img, message)

        # Save as lossless PNG
        out_filename = f"stego_{out_basename}.png"
        out_path = os.path.join(app.config['OUTPUT_FOLDER'], out_filename)
        saved = cv2.imwrite(out_path, stego_img, [cv2.IMWRITE_PNG_COMPRESSION, 0])
        if not saved:
            return jsonify({'error': 'Failed to save stego image.'}), 500

        logger.info(f"Stego image saved: {out_path}")
        return jsonify({'success': True, 'output_url': f'/{out_path}'})

    except ValueError as e:
        logger.error(f"Embedding error: {e}")
        return jsonify({'error': f'Embedding failed: {e}'}), 500
    except Exception as e:
        logger.error(f"Embedding failed: {e}")
        return jsonify({'error': str(e)}), 500


@app.route('/extract', methods=['POST'])
def handle_extract():
    if 'image' not in request.files:
        return jsonify({'error': 'Missing image'}), 400

    file = request.files['image']
    if file.filename == '':
        return jsonify({'error': 'No file selected'}), 400

    filename = secure_filename(file.filename)
    input_path = os.path.join(app.config['UPLOAD_FOLDER'], f"extracting_{filename}")
    file.save(input_path)

    try:
        enc_bytes = extract_data(input_path)
        if not enc_bytes:
            return jsonify({'error': 'No hidden data found in this image. Make sure you are uploading the exact stego PNG generated by this system.'}), 500

        msg = decrypt_message(enc_bytes)
        if msg and not msg.startswith('[ERROR]'):
            logger.info(f"Successfully extracted message: '{msg[:40]}...'")
            return jsonify({'success': True, 'message': msg})
        else:
            logger.warning(f"Decryption failed: {msg}")
            return jsonify({
                'error': f'Decryption failed. The image may not contain hidden data generated by this system, or the file was modified/compressed after embedding. Technical detail: {msg}'
            }), 500

    except Exception as e:
        logger.error(f"Extraction error: {e}")
        return jsonify({'error': str(e)}), 500


@app.route('/detect', methods=['POST'])
def handle_detect():
    if 'image' not in request.files:
        return jsonify({'error': 'Missing image'}), 400

    file = request.files['image']
    if file.filename == '':
        return jsonify({'error': 'No file selected'}), 400

    if not allowed_file(file.filename):
        return jsonify({'error': 'Invalid file type. Upload PNG or JPG.'}), 400

    filename = secure_filename(file.filename)
    input_path = os.path.join(app.config['UPLOAD_FOLDER'], f"detect_{filename}")
    file.save(input_path)

    try:
        label, confidence = predict_image(input_path)
        if label is None:
            return jsonify({'error': 'Detection failed. Ensure the model is trained (python cli.py train).'}), 500

        is_stego = (label == 'Stego Image')
        logger.info(f"Detection: {label} ({confidence:.2f}%)")

        return jsonify({
            'success': True,
            'label': label,
            'confidence': round(confidence, 2),
            'is_stego': is_stego,
            'preview_url': f'/{input_path}'
        })
    except Exception as e:
        logger.error(f"Detection error: {e}")
        return jsonify({'error': str(e)}), 500


if __name__ == '__main__':
    app.run(debug=True, port=5000)
